systemname: typhoid
flexget_check_frequency: 15
email: null
rootDownloadPath: /var/lib/kapture/downloads
moviesPath: movies
showsPath: tvshows
musicPath: music
photosPath: photos
defaultMediaPath: downloads
plugins:
    com.piratebay:
        enabled: true
    com.youtube:
        enabled: true
    info.showrss:
        enabled: true
    com.transmissionbt:
        enabled: true
        transmission_host: transmission
        transmission_port: 9091
        transmission_user: admin
        transmission_pass: password
    com.flexget:
        enabled: true
        flexget_host: flexget
        flexget_port: 5050
        api_token: null
        flexget_user: flexget
        flexget_pass: mySuperPassword
    com.kapture.url:
        enabled: true
